language: node_js
node_js:
  - 'lts/*'

jobs:
  include:
    - stage: test
      node_js: '8'
      script: npm run test
    - stage: npm release
      node_js: '8'
      script: echo 'Deploying to npm ...'
      deploy:
        - provider: npm
          email: 'devmonk@mediamonks.com'
          api_key: $NPM_TOKEN
          on:
            tags: true
            node: '8'
          skip_cleanup: true